USE ClubDeportivo;

insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (786584, 'NATACION', 'ARANCELADA');
insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (807376, 'PILATES', 'ARANCELADA');
insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (867976, 'VOLEY', 'ARANCELADA');
insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (846978, 'TENIS', 'ARANCELADA');
insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (727967, 'HOCKEY', 'ARANCELADA');
insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (806584, 'PATIN', 'ARANCELADA');
insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (777765, 'MMA', 'ARANCELADA');

insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (897971, 'YOGA', 'GRATUITA');
insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (908577, 'ZUMBA', 'GRATUITA');
insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (708584, 'FUTBOL', 'GRATUITA');
insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (717377, 'GIMNASIA', 'GRATUITA');
insert into ACTIVIDAD (COD_ACTIVIDAD, NOMBRE_ACT, COSTO) values (676578, 'CANTO', 'GRATUITA');


