insert into CATEGORIA (COD_CATEGORIA, TIPO_CATEGORIA) values (0317, 'INFANTIL');
insert into CATEGORIA (COD_CATEGORIA, TIPO_CATEGORIA) values (1840, 'MAYOR');
insert into CATEGORIA (COD_CATEGORIA, TIPO_CATEGORIA) values (4165, 'VITALICIO');

insert into INFANTIL (COD_CATEGORIA, TIPO_CATEGORIA) values (0317, 20.00);
insert into MAYOR (COD_CATEGORIA, TIPO_CATEGORIA) values (1840, 35.50);
insert into VITALICIO (COD_CATEGORIA, TIPO_CATEGORIA) values (4165, 20.00);
