USE ClubDeportivo;

SELECT *
FROM CATEGORIA;

SELECT
    GF.NRO_SOCIO_TITULAR AS NRO_SOCIO_TITULAR,
    S.NOMBRE_SOCIO AS NOMBRE_SOCIO_TITULAR,
    S.APELLIDO_SOCIO AS APELLIDO_SOCIO_TITULAR,
    COUNT(*) AS CANTIDAD_INTEGRANTES,
    SUM(CM.IMPORTE_A_PAGAR) AS IMPORTE_TOTAL_ADEUDADO
FROM
    GRUPO_FAMILIAR GF
    INNER JOIN SOCIO S ON GF.NRO_GRUPO = S.NRO_GRUPO
    INNER JOIN CUOTA_SOCIAL CS ON S.NRO_GRUPO = CS.NRO_GRUPO AND S.NRO_SOCIO = CS.NRO_SOCIO
    INNER JOIN CUOTA_MENSUAL CM ON CS.COD_CUOTA_MENSUAL = CM.COD_CUOTA_MENSUAL
WHERE
    YEAR(CS.VIGENCIA_CUOTA_SOCIAL) = YEAR(CURDATE())  -- Adeudan cuotas del año en curso
GROUP BY
    GF.NRO_SOCIO_TITULAR, S.NOMBRE_SOCIO, S.APELLIDO_SOCIO;
