USE ClubDeportivo;

CREATE VIEW Deudores_anio_corriente AS
SELECT
    GF.NRO_SOCIO_TITULAR AS NRO_SOCIO_TITULAR,
    S.NOMBRE_SOCIO AS NOMBRE_SOCIO_TITULAR,
    S.APELLIDO_SOCIO AS APELLIDO_SOCIO_TITULAR,
    COUNT(DISTINCT S.NRO_SOCIO) AS CANTIDAD_INTEGRANTES,
    SUM(CM.IMPORTE_A_PAGAR) AS IMPORTE_TOTAL_ADEUDADO
FROM
    GRUPO_FAMILIAR GF
    INNER JOIN SOCIO S ON GF.NRO_GRUPO = S.NRO_GRUPO
    INNER JOIN CUOTA_SOCIAL CS ON S.NRO_GRUPO = CS.NRO_GRUPO AND S.NRO_SOCIO = CS.NRO_SOCIO
    INNER JOIN CUOTA_MENSUAL CM ON CS.COD_CUOTA_MENSUAL = CM.COD_CUOTA_MENSUAL
WHERE
    CS.VIGENCIA_CUOTA_SOCIAL < CURDATE()
    AND YEAR(CS.VIGENCIA_CUOTA_SOCIAL) = YEAR(CURDATE())
GROUP BY
    GF.NRO_SOCIO_TITULAR, S.NOMBRE_SOCIO, S.APELLIDO_SOCIO;


CREATE VIEW Socios_act_gratis AS
SELECT C.TIPO_CATEGORIA, COUNT(DISTINCT P.NRO_SOCIO) AS CANTIDAD_SOCIOS
FROM CATEGORIA AS C
INNER JOIN POSEE AS P ON C.COD_CATEGORIA = P.COD_CATEGORIA
INNER JOIN SE_INSCRIBE AS SI ON P.NRO_SOCIO = SI.NRO_SOCIO
INNER JOIN CRONOGRAMA AS CR ON SI.COD_CRONOGRAMA = CR.COD_CRONOGRAMA
INNER JOIN ACTIVIDAD AS ACT ON CR.COD_ACTIVIDAD = ACT.COD_ACTIVIDAD
WHERE YEAR(CR.PERIODO) = YEAR(CURDATE()) - 1
AND ACT.COSTO = 'GRATUITA'
GROUP BY C.TIPO_CATEGORIA
HAVING COUNT(DISTINCT ACT.COD_ACTIVIDAD) = (SELECT COUNT(*) 
                                            FROM ACTIVIDAD
                                            WHERE COSTO = 'GRATUITA');
                                            
CREATE VIEW Cronograma_Activo AS							
SELECT NOMBRE_ACT, FECHA_TURNO, HORARIO
FROM CRONOGRAMA AS CR
INNER JOIN ACTIVIDAD AS ACT ON CR.COD_ACTIVIDAD = ACT.COD_ACTIVIDAD
INNER JOIN TURNO AS T ON CR.COD_TURNO = T.COD_TURNO
ORDER BY FECHA_TURNO;


CREATE VIEW SOCIOS_INSCRIPTOS AS
SELECT NRO_GRUPO, NRO_SOCIO, NOMBRE_ACT, FECHA_TURNO, HORARIO
FROM SE_INSCRIBE AS SE
INNER JOIN CRONOGRAMA AS CR ON SE.COD_CRONOGRAMA =CR.COD_CRONOGRAMA
INNER JOIN ACTIVIDAD AS ACT ON CR.COD_ACTIVIDAD = ACT.COD_ACTIVIDAD
INNER JOIN TURNO AS T ON CR.COD_TURNO = T.COD_TURNO;

SELECT *
FROM Deudores_anio_corriente;

SELECT COD_CRONOGRAMA, NOMBRE_ACT, FECHA_TURNO, HORARIO
FROM CRONOGRAMA AS CR
INNER JOIN ACTIVIDAD AS ACT ON CR.COD_ACTIVIDAD = ACT.COD_ACTIVIDAD
INNER JOIN TURNO AS T ON CR.COD_TURNO = T.COD_TURNO
ORDER BY FECHA_TURNO;

