DELETE FROM GRUPO_FAMILIAR;

USE ClubDeportivo;

insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (1, '903 Sycamore Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (2, '925 Dayton Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (3, '11 Hermina Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (4, '821 Cambridge Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (5, '46 Rusk Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (6, '412 Graedel Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (7, '9269 Fordem Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (8, '6598 Meadow Ridge Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (9, '2346 Boyd Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (10, '33147 Dryden Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (11, '15542 Sommers Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (12, '1141 Drewry Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (13, '7 Packers Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (14, '98 Knutson Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (15, '11 Shelley Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (16, '3 Thackeray Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (17, '664 Bultman Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (18, '017 Superior Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (19, '969 Moulton Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (20, '20 Nobel Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (21, '10901 Morrow Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (22, '3 Arkansas Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (23, '5 Stone Corner Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (24, '248 Pepper Wood Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (25, '385 Kim Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (26, '150 Swallow Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (27, '05379 Bartillon Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (28, '20 Pepper Wood Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (29, '9 Lakewood Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (30, '5 Fairview Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (31, '946 Karstens Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (32, '90 Dovetail Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (33, '6021 Oakridge Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (34, '6 Ridgeview Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (35, '4 American Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (36, '453 Merry Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (37, '45 Blaine Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (38, '2221 Harbort Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (39, '3 Eggendart Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (40, '6002 Del Mar Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (41, '05677 Spaight Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (42, '61764 Graedel Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (43, '494 Miller Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (44, '34 Jenifer Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (45, '9 Eliot Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (46, '91956 Clyde Gallagher Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (47, '8 Hallows Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (48, '06 Arizona Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (49, '6 Heath Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (50, '48 Jana Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (51, '38713 Carpenter Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (52, '98721 Hanover Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (53, '68 Ilene Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (54, '50 Laurel Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (55, '306 Stuart Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (56, '4 Hazelcrest Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (57, '61 Carpenter Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (58, '6245 Melrose Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (59, '5443 Talmadge Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (60, '55692 Golden Leaf Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (61, '48 New Castle Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (62, '153 Manitowish Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (63, '235 Sullivan Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (64, '40566 Maple Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (65, '1 Ridgeview Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (66, '8681 Oak Valley Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (67, '4698 Golden Leaf Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (68, '49907 Dawn Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (69, '99786 Stuart Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (70, '54229 Mendota Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (71, '067 Cherokee Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (72, '77061 Loomis Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (73, '69 West Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (74, '47 Talmadge Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (75, '6156 Forster Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (76, '74323 Dorton Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (77, '31 Redwing Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (78, '50 Mosinee Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (79, '00034 Schlimgen Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (80, '603 Iowa Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (81, '01 Oakridge Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (82, '2 Dexter Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (83, '91 Warbler Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (84, '9584 Mifflin Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (85, '85 Starling Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (86, '980 Gina Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (87, '023 Carey Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (88, '65353 Melody Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (89, '036 Vera Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (90, '7 Farmco Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (91, '66 Straubel Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (92, '787 Tennessee Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (93, '39 American Ash Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (94, '4338 Ronald Regan Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (95, '85065 Towne Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (96, '1744 Westend Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (97, '0393 Mifflin Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (98, '53 Almo Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (99, '04014 Stang Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (100, '41 Hazelcrest Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (101, '166 Upham Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (102, '43329 Browning Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (103, '4 Sunfield Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (104, '7236 Steensland Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (105, '30 Melvin Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (106, '41587 Emmet Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (107, '91227 Oak Valley Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (108, '4 Roth Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (109, '6900 Gerald Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (110, '97 Sherman Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (111, '3097 Service Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (112, '2929 Spenser Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (113, '91 Birchwood Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (114, '0888 Everett Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (115, '4 Stone Corner Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (116, '43929 Londonderry Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (117, '99 Sachtjen Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (118, '729 Corry Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (119, '129 Acker Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (120, '1793 Badeau Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (121, '96617 Portage Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (122, '6 Columbus Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (123, '7 Farwell Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (124, '93 8th Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (125, '36001 Kinsman Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (126, '5663 Hanson Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (127, '8 Norway Maple Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (128, '327 Lotheville Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (129, '01179 Swallow Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (130, '061 Lunder Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (131, '32 Randy Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (132, '1591 Namekagon Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (133, '799 Bowman Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (134, '596 Bowman Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (135, '37182 Prairieview Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (136, '57263 Kedzie Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (137, '22 Algoma Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (138, '77 Carpenter Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (139, '8181 East Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (140, '440 Carioca Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (141, '96 Susan Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (142, '94 Kedzie Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (143, '943 Express Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (144, '03 Beilfuss Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (145, '9262 Brickson Park Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (146, '7 Victoria Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (147, '60 Rieder Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (148, '93321 Maple Wood Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (149, '18 Judy Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (150, '2461 Manley Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (151, '6 Schlimgen Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (152, '426 Logan Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (153, '2 Claremont Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (154, '0736 Alpine Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (155, '72113 Monterey Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (156, '350 Sherman Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (157, '531 Cody Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (158, '906 Green Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (159, '7989 Dayton Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (160, '8360 Mitchell Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (161, '560 Mifflin Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (162, '243 Forest Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (163, '4 Riverside Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (164, '33 Sherman Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (165, '12 School Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (166, '67614 Bonner Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (167, '9240 Carey Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (168, '7 Pennsylvania Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (169, '67 Superior Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (170, '28633 Glendale Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (171, '91921 Autumn Leaf Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (172, '45 Buell Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (173, '51061 Caliangt Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (174, '82 Kipling Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (175, '06 Anthes Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (176, '18 Everett Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (177, '747 Victoria Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (178, '46733 Anthes Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (179, '45116 Meadow Ridge Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (180, '96134 Pleasure Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (181, '59661 Commercial Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (182, '0219 Pankratz Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (183, '58744 Transport Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (184, '38206 Northwestern Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (185, '20 Laurel Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (186, '515 Hagan Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (187, '5379 Fieldstone Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (188, '40654 Canary Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (189, '77 Ridgeview Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (190, '04896 Shoshone Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (191, '8 Kedzie Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (192, '6909 Mallory Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (193, '9402 Vahlen Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (194, '077 Johnson Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (195, '9 North Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (196, '65 Scott Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (197, '93293 Dryden Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (198, '274 Autumn Leaf Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (199, '978 Grim Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (200, '2 Killdeer Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (201, '0052 Birchwood Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (202, '261 5th Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (203, '37787 Petterle Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (204, '0138 Lakewood Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (205, '64 1st Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (206, '539 Fordem Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (207, '22 Ridge Oak Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (208, '1 Thompson Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (209, '4 Hazelcrest Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (210, '9308 Eliot Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (211, '32903 Delaware Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (212, '60 Mayer Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (213, '4 Annamark Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (214, '81 Iowa Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (215, '3011 Talisman Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (216, '5 Leroy Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (217, '0908 Burning Wood Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (218, '538 Main Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (219, '4235 Anhalt Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (220, '4246 Bashford Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (221, '88 Dunning Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (222, '99564 Graedel Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (223, '5 Garrison Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (224, '27 Dottie Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (225, '791 Vermont Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (226, '13277 Michigan Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (227, '33 Old Gate Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (228, '311 Dwight Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (229, '6041 Straubel Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (230, '0173 Shoshone Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (231, '68 Carioca Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (232, '780 Elmside Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (233, '079 Warner Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (234, '6 Rigney Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (235, '2107 Darwin Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (236, '2 Carioca Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (237, '716 Dapin Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (238, '2136 Pankratz Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (239, '5 Schurz Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (240, '2185 Service Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (241, '9813 Dryden Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (242, '780 Lindbergh Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (243, '74533 Blackbird Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (244, '7180 Crescent Oaks Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (245, '67 Towne Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (246, '561 New Castle Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (247, '0409 Debra Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (248, '847 Mallard Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (249, '44549 Homewood Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (250, '0 Haas Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (251, '43 Northfield Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (252, '2 Porter Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (253, '858 Paget Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (254, '75 Lindbergh Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (255, '6735 Fisk Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (256, '7 Barby Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (257, '3 Weeping Birch Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (258, '1 Forster Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (259, '36050 Ohio Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (260, '26087 Debs Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (261, '1838 Washington Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (262, '86 Rigney Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (263, '86 Kedzie Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (264, '1014 Mayfield Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (265, '0803 Victoria Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (266, '667 Jenna Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (267, '71831 Calypso Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (268, '2 Kim Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (269, '30 Division Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (270, '7795 Elgar Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (271, '1960 Goodland Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (272, '162 Loomis Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (273, '83 Algoma Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (274, '364 Old Shore Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (275, '6 Florence Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (276, '3 Bluejay Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (277, '19 Little Fleur Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (278, '71 Karstens Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (279, '7 Manufacturers Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (280, '681 Morningstar Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (281, '82 Hazelcrest Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (282, '63 Caliangt Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (283, '2 Chinook Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (284, '8 Emmet Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (285, '3 Bonner Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (286, '5206 Comanche Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (287, '05 Nancy Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (288, '31 Bunker Hill Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (289, '84915 Washington Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (290, '68257 Bartelt Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (291, '96722 Graceland Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (292, '7587 Hayes Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (293, '8138 Cherokee Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (294, '0 Hallows Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (295, '08 Stoughton Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (296, '43 Gina Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (297, '19068 Continental Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (298, '33126 Morrow Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (299, '380 4th Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (300, '40318 Hallows Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (301, '831 Duke Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (302, '48148 Clarendon Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (303, '23 Scoville Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (304, '8955 Hintze Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (305, '28 Kensington Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (306, '51850 Monument Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (307, '63 Del Mar Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (308, '2063 Moose Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (309, '97159 Lyons Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (310, '7 Dennis Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (311, '8255 Division Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (312, '35342 Walton Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (313, '1 Old Gate Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (314, '269 Erie Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (315, '4 Prairieview Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (316, '97472 Red Cloud Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (317, '1194 Mallory Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (318, '990 Tennyson Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (319, '18959 Schmedeman Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (320, '4024 Golden Leaf Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (321, '35 Pierstorff Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (322, '17922 Grim Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (323, '013 New Castle Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (324, '44 Maywood Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (325, '6590 Truax Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (326, '64 Scoville Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (327, '67158 Straubel Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (328, '65745 Cody Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (329, '1 Ridge Oak Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (330, '6233 Nancy Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (331, '43 Pawling Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (332, '764 Warrior Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (333, '37526 Grasskamp Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (334, '40363 Mariners Cove Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (335, '42 Bonner Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (336, '06 Blue Bill Park Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (337, '98450 Bartelt Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (338, '42 Shoshone Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (339, '1 Trailsway Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (340, '402 Fuller Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (341, '4 Loomis Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (342, '22 Hayes Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (343, '800 Brentwood Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (344, '011 Scoville Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (345, '75 Weeping Birch Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (346, '46324 Old Gate Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (347, '3500 Cascade Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (348, '00 Clove Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (349, '97975 Lien Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (350, '38 Dayton Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (351, '2 Holmberg Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (352, '756 Judy Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (353, '273 Katie Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (354, '18 Green Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (355, '0726 Pine View Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (356, '47687 Drewry Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (357, '23 Raven Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (358, '6723 Texas Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (359, '47637 Melby Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (360, '866 Merchant Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (361, '2 Riverside Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (362, '7305 Thompson Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (363, '8 Hoffman Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (364, '5212 Bunting Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (365, '82810 Harper Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (366, '33667 Jenifer Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (367, '24 Hallows Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (368, '1 Crownhardt Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (369, '35 Mandrake Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (370, '343 Vermont Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (371, '010 Clarendon Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (372, '56 Washington Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (373, '6 Di Loreto Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (374, '95444 Oxford Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (375, '42 East Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (376, '11 Pleasure Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (377, '6 Bunker Hill Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (378, '3472 Dennis Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (379, '85 Pearson Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (380, '7 Victoria Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (381, '63 Roth Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (382, '195 Mayfield Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (383, '51306 Anthes Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (384, '731 Laurel Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (385, '6 Helena Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (386, '542 Schlimgen Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (387, '2 Armistice Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (388, '953 New Castle Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (389, '96 Carey Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (390, '40007 Armistice Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (391, '358 Lunder Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (392, '3 Barnett Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (393, '234 South Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (394, '5484 Bunker Hill Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (395, '53797 Garrison Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (396, '45448 Meadow Vale Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (397, '5289 Butternut Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (398, '8 Waywood Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (399, '7875 Melvin Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (400, '6 Melby Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (401, '5 Westerfield Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (402, '457 Shopko Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (403, '62 Sutteridge Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (404, '584 Mayfield Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (405, '1949 Katie Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (406, '62 Forest Run Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (407, '2025 Warner Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (408, '151 Brown Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (409, '086 New Castle Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (410, '5 Crownhardt Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (411, '39 Toban Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (412, '51 Maywood Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (413, '2 Raven Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (414, '78491 Corry Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (415, '22130 Marcy Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (416, '0930 Charing Cross Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (417, '467 Harper Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (418, '421 Katie Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (419, '39238 Susan Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (420, '11958 Green Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (421, '83149 Morningstar Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (422, '85116 Acker Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (423, '3 Kenwood Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (424, '9648 David Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (425, '98 Mcbride Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (426, '12688 Wayridge Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (427, '5588 Maryland Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (428, '100 Brentwood Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (429, '9 Steensland Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (430, '87275 Victoria Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (431, '7660 Dapin Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (432, '5 7th Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (433, '532 Pennsylvania Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (434, '629 Stuart Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (435, '898 Burning Wood Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (436, '1 Pearson Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (437, '982 John Wall Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (438, '758 Birchwood Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (439, '5530 Waubesa Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (440, '8643 Green Ridge Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (441, '3 3rd Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (442, '479 Petterle Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (443, '7 Prairieview Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (444, '5 Holmberg Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (445, '22690 High Crossing Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (446, '7448 Pawling Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (447, '55 Waxwing Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (448, '501 Laurel Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (449, '2876 Sloan Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (450, '366 Golf Course Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (451, '96 Reindahl Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (452, '8232 Swallow Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (453, '149 Eliot Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (454, '9 International Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (455, '24 Rockefeller Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (456, '42681 Raven Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (457, '81148 Truax Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (458, '499 Sachtjen Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (459, '80 Magdeline Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (460, '610 Mcguire Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (461, '8 Stoughton Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (462, '33169 Kim Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (463, '6015 Helena Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (464, '7 Ludington Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (465, '92 Michigan Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (466, '8183 Sutteridge Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (467, '4 Autumn Leaf Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (468, '55347 Lukken Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (469, '017 Union Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (470, '323 Lakeland Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (471, '65 Mockingbird Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (472, '59 Colorado Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (473, '61 Tennessee Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (474, '67 Dottie Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (475, '1 Merchant Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (476, '7510 Express Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (477, '9622 Washington Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (478, '92443 Johnson Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (479, '61702 Manitowish Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (480, '691 Hooker Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (481, '6216 Crownhardt Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (482, '7 Merrick Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (483, '365 Russell Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (484, '98 Elmside Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (485, '96664 Vernon Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (486, '4 Crescent Oaks Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (487, '84 Fairview Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (488, '2 Rowland Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (489, '8931 Milwaukee Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (490, '9 Bay Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (491, '28193 Stang Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (492, '40 2nd Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (493, '13 Moland Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (494, '5 Red Cloud Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (495, '6 Mayer Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (496, '59 Badeau Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (497, '58616 Granby Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (498, '52128 Cordelia Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (499, '9 Muir Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (500, '5267 Hallows Junction');

