DELETE FROM GRUPO_FAMILIAR;

USE ClubDeportivo;

insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (1, '903 Sycamore Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (2, '925 Dayton Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (3, '11 Hermina Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (4, '821 Cambridge Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (5, '46 Rusk Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (6, '412 Graedel Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (7, '9269 Fordem Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (8, '6598 Meadow Ridge Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (9, '2346 Boyd Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (10, '33147 Dryden Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (11, '15542 Sommers Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (12, '1141 Drewry Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (13, '7 Packers Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (14, '98 Knutson Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (15, '11 Shelley Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (16, '3 Thackeray Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (17, '664 Bultman Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (18, '017 Superior Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (19, '969 Moulton Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (20, '20 Nobel Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (21, '10901 Morrow Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (22, '3 Arkansas Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (23, '5 Stone Corner Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (24, '248 Pepper Wood Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (25, '385 Kim Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (26, '150 Swallow Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (27, '05379 Bartillon Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (28, '20 Pepper Wood Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (29, '9 Lakewood Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (30, '5 Fairview Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (31, '946 Karstens Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (32, '90 Dovetail Terrace');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (33, '6021 Oakridge Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (34, '6 Ridgeview Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (35, '4 American Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (36, '453 Merry Park');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (37, '45 Blaine Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (38, '2221 Harbort Drive');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (39, '3 Eggendart Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (40, '6002 Del Mar Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (41, '05677 Spaight Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (42, '61764 Graedel Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (43, '494 Miller Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (44, '34 Jenifer Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (45, '9 Eliot Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (46, '91956 Clyde Gallagher Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (47, '8 Hallows Place');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (48, '06 Arizona Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (49, '6 Heath Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (50, '48 Jana Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (51, '38713 Carpenter Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (52, '98721 Hanover Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (53, '68 Ilene Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (54, '50 Laurel Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (55, '306 Stuart Plaza');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (56, '4 Hazelcrest Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (57, '61 Carpenter Avenue');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (58, '6245 Melrose Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (59, '5443 Talmadge Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (60, '55692 Golden Leaf Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (61, '48 New Castle Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (62, '153 Manitowish Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (63, '235 Sullivan Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (64, '40566 Maple Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (65, '1 Ridgeview Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (66, '8681 Oak Valley Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (67, '4698 Golden Leaf Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (68, '49907 Dawn Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (69, '99786 Stuart Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (70, '54229 Mendota Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (71, '067 Cherokee Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (72, '77061 Loomis Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (73, '69 West Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (74, '47 Talmadge Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (75, '6156 Forster Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (76, '74323 Dorton Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (77, '31 Redwing Alley');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (78, '50 Mosinee Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (79, '00034 Schlimgen Parkway');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (80, '603 Iowa Junction');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (81, '01 Oakridge Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (82, '2 Dexter Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (83, '91 Warbler Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (84, '9584 Mifflin Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (85, '85 Starling Pass');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (86, '980 Gina Crossing');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (87, '023 Carey Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (88, '65353 Melody Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (89, '036 Vera Trail');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (90, '7 Farmco Lane');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (91, '66 Straubel Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (92, '787 Tennessee Street');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (93, '39 American Ash Hill');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (94, '4338 Ronald Regan Court');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (95, '85065 Towne Center');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (96, '1744 Westend Point');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (97, '0393 Mifflin Road');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (98, '53 Almo Circle');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (99, '04014 Stang Way');
insert into GRUPO_FAMILIAR (NRO_GRUPO, DOMICILIO) values (100, '41 Hazelcrest Park');
