USE Clubdeportivo;

INSERT INTO AREA (COD_AREA, UBICACION, CAPACIDAD, MANTENIMIENTO, ACTIVIDADES) VALUES (1000, 'Sala de uso recreativo', 40, 'Semanal', 'YOGA, MMA, CANTO');
INSERT INTO AREA (COD_AREA, UBICACION, CAPACIDAD, MANTENIMIENTO, ACTIVIDADES) VALUES (1001, 'Gimnasio', 100, 'Semanal', 'ZUMBA, PILATES, VOLEY, GIMNASIA ARTISTICA, PATIN ARTISTICO');
INSERT INTO AREA (COD_AREA, UBICACION, CAPACIDAD, MANTENIMIENTO, ACTIVIDADES) VALUES (1002, 'Piscina', 50, 'Mensual', 'NATACION');
INSERT INTO AREA (COD_AREA, UBICACION, CAPACIDAD, MANTENIMIENTO, ACTIVIDADES) VALUES (1003, 'Cancha de Futbol', 150, 'Semanal', 'FUTBOL');
INSERT INTO AREA (COD_AREA, UBICACION, CAPACIDAD, MANTENIMIENTO, ACTIVIDADES) VALUES (1004, 'Cancha de Hockey', 150, 'Semanal', 'HOCKEY');
INSERT INTO AREA (COD_AREA, UBICACION, CAPACIDAD, MANTENIMIENTO, ACTIVIDADES) VALUES (1005, 'Cancha de Tenis', 50, 'Semanal', 'TENIS');
